version: '3.8'

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: tanknam
      MINIO_ROOT_PASSWORD: "12345678"
    volumes:
      - ./backend/app/minio/data:/data
    command: server /data --console-address ":9001"
